version: 2

project_name: importgoblin

builds:
- id: importgoblin
  main: ./main.go
  binary: importgoblin
  goos:
    - linux
  goarch:
    - amd64
  env:
    - CGO_ENABLED=1
  ldflags:
    - -s
    - -w

archives:
- formats:
  - binary
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: goblain
    name: importgoblin

changelog:
  use: git
  filters:
    exclude:
      - '^docs?:'
      - '^test:'
      - '^chore:'
