name: Release

on:
  push:
    tags:
    - 'v*'
    branches:
    - master

jobs:
  release:
    name: Release from tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release ${{ startsWith(github.ref, 'refs/tags/') && '' || '--snapshot' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
